name: GmodOnlineDiscordBot NativeAOT Build & Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write 

env:
  DOTNET_VERSION: '9.0.x'
  RUNTIME_ID: 'linux-x64'
  PUBLISH_DIR: 'publish'
  ARTIFACT_NAME: 'GmodOnlineDiscordBot'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish NativeAOT
        run: |
          dotnet publish -c Release -r ${{ env.RUNTIME_ID }} \
            -p:PublishAot=true \
            -p:StripSymbols=true \
            -p:SelfContained=true \
            --output ${{ env.PUBLISH_DIR }}

      - name: Create ZIP archive
        run: |
          cd ${{ env.PUBLISH_DIR }}
          zip -r ../${{ env.ARTIFACT_NAME }}.zip *
          ls ../${{ env.ARTIFACT_NAME }}.zip
          
      - name: Debug Tag
        run: echo "tag IS v$(date +%d.%m.%Y)"

      - name: Upload to Release
        #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARTIFACT_NAME }}.zip
          tag_name: "v$(date +%d.%m.%Y)"
          draft: false
          prerelease: false
          generate_release_notes: true
