name: Publish NativeAOT Release

on:
  push:
    branches: [ master ]
  create:
    tags: [ 'v*' ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Publish NativeAOT (linux-x64)
      run: |
        dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishAot=true /p:PublishSingleFile=true
        ls -R ./bin/Release/net9.0/linux-x64/publish/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: "NativeAOT for linux-x64"
        files: |
          ./bin/Release/net9.0/linux-x64/publish/*